### ISSUE TITLE
Getting stuck after first three stompers

### ISSUE THREAD

**Issue by Moe1992** [ShootMe/OriDETAS#3]
Hi ShootMe,
I have a problem with the includes tas files. Regardless of which one I choose I do get to the point where the three stompers attack but afterwards I get stuck as I don't get on the ledge with that one jump. I add a link to a gif that shows the problem. Any ideas why it wouldn't work?
https://gfycat.com/EnchantedPastelFunnelweaverspider

I tried changing between full screen and windowed but it didn't help. Also I am playing the german version. Can this be a problem?

Thanks in advance!
Moe

**Comment by ShootMe** [comment]
It's hard to say. Wouldn't be language related. Most desyncs are performance related, so depending on your computer it may get off slightly.
I also don't know what version you are trying, All Cells, Any%, or All Skills.

Regardless, there isn't too much I can do. You'll probably have to modify the files slightly to get it to work on your computer.

If you want help, you can join the Ori Discord server listed on speedrun.com. There is a #TAS channel for this type of thing.
